<Project Sdk="Microsoft.NET.Sdk.Worker">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>dotnet-WorkerService1-3e5fc31f-eac7-444f-9be0-7214c535b138</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
	  <Content Remove="Properties\launchSettings.json" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="Properties\launchSettings.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.1" />
		<PackageReference Include="Newtonsoft.Json" Version="9.0.1" />
		<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
	</ItemGroup>
</Project>
